# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2de954046ab08060d66fc13064c5598beca8b7e0ff0985119d86811b584a0fd09f5dcc58266f6ed95e744e15554e67f13c307f6922b3815f0152b871b584056

test:
  secret_key_base: f53bd609fcb4c04432f563c1237237a1a77ffa219913c3754012cf6b69090c9ec45ada5da2146523c86b85255553ab447da7484bcaea041db01a0305250ea86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
